### PR TITLE
[#961] Fix master build: use pgagroal_as_bool for server_reset_query_always

### LINKED ISSUE #961: master fails to build: #941 calls as_bool, renamed to pgagroal_as_bool by #871
master is currently red on every build job. dee3afb (#941) added `pgagroal_apply_main_configuration` handling for `server_reset_query_always` calling `as_bool(...)`; 6723f09 (#871) then renamed the validation helpers to `pgagroal_as_*`. The two merged without textual conflict, so the semantic conflict only shows at compile time:

```
src/libpgagroal/configuration.c:6207:11: error: implicit declaration of function 'as_bool'; did you mean 'to_bool'?
```

It is the only remaining un-prefixed `as_*` call site on master. One-line fix, PR follows. This currently fails CI on every open PR's merge build as well.

### PR DESCRIPTION
**Pull request by fheikens**
Fixes the build break on master (close #961): #941 and #871 merged without textual conflict, leaving one call to the pre-rename as_bool() in pgagroal_apply_main_configuration. Verified the full build passes locally with the change; this also unblocks CI on every open PR, since merge builds against master currently fail.

### CODE REVIEW

**Comment by fheikens** [comment]
For the record: the two red FreeBSD jobs here failed at the 'Setup FreeBSD VM' step before any compile — the same VM-provisioning failure is hitting every PR today (#907, #960 included). All build jobs that actually ran (Linux gcc/clang Debug+Release, macOS, RPM, format-check) pass.

**Comment by Userfrom1995** [comment]
@fheikens Thank you for your contribution.
