### ISSUE TITLE
`pgagroal-config` needs to validate user input

### ISSUE THREAD

**Issue by fluca1978** [agroal/pgagroal#871]
`pgagroal-config` should use the `as_xxx` functions to validate user input for the configuration parameters, in this way it will prompt again if the user inserts something wrong.
As an example of the current behavior:

```
% pgagroal-config init
pgagroal configuration generator
================================

--- [pgagroal] section ---

Host (bind address) [*]: 
Port (required) [2345]: 
Unix socket directory [/tmp/]: 
Max connections [100]: a
Idle timeout (seconds, 0 to disable) [600]: no
Validation (off, foreground, background) [off]: ffo
Event backend (auto, io_uring, epoll, kqueue) [auto]: 
Metrics port (0 to disable) [5081]: 
Management port (0 to disable) [5082]: 
Log type (console, file, syslog) [file]: 
Log level (fatal, error, warn, info, debug, trace) [info]:
```

note the `ffo` and `a` input values.

This requires the `as_xxx` functions defined in `config.c` to be made project-wide available (i.e., not static).

Another approach could be to accept all the input values, then run a validation against the configuration file to see if there are errors.
Partially related to #869 and #870 since hits `pgagroal-config`.

**Comment by rohanmishra29** [comment]
Hi, I'd like to work on this issue , could you assign it to me?

**Comment by jesperpedersen** [comment]
@rohanmishra29 Go for it !

**Comment by fluca1978** [comment]
@rohanmishra29 thanks for picking this, please consider that we need to validate user input in both `pgagroal-config` and the internal `pgagroal` configuration loading, hence the most we can share the validation code, the better.

**Comment by fluca1978** [comment]
Building on mac osx is failing:
```
[ 14%] Building C object src/CMakeFiles/pgagroal.dir/libpgagroal/connection.c.o
/Users/runner/work/pgagroal/pgagroal/src/libpgagroal/configuration.c:6207:11: error: call to undeclared function 'as_bool'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
 6207 |       if (as_bool(value, &config->server_reset_query_always))
      |           ^

```

there is an invalid forward reference, @rohanmishra29 please fix.
Why is this not caught by the building?

**Comment by rohanmishra29** [comment]
@fluca1978 ,apologies for missing that case. The server_reset_query_always call was added in commit dee3afb (#941) after my rename, so it wasn't covered. I see it is already fixed in e19d708 ,thank you.

**Comment by fluca1978** [comment]
Closed via #961 .
Why was not detected during the CI test in here?

**Comment by rohanmishra29** [comment]
@fluca1978 , the server_reset_query_always call was introduced in #941, which was merged to master after my PR was submitted. When my CI ran, that code didn't exist yet, so there was nothing to catch. The rename was complete at the time of testing ,the conflict only arose when #941 landed on master afterward.
