### ISSUE TITLE
master fails to build: #941 calls as_bool, renamed to pgagroal_as_bool by #871

### ISSUE THREAD

**Issue by fheikens** [agroal/pgagroal#961]
master is currently red on every build job. dee3afb (#941) added `pgagroal_apply_main_configuration` handling for `server_reset_query_always` calling `as_bool(...)`; 6723f09 (#871) then renamed the validation helpers to `pgagroal_as_*`. The two merged without textual conflict, so the semantic conflict only shows at compile time:

```
src/libpgagroal/configuration.c:6207:11: error: implicit declaration of function 'as_bool'; did you mean 'to_bool'?
```

It is the only remaining un-prefixed `as_*` call site on master. One-line fix, PR follows. This currently fails CI on every open PR's merge build as well.
